groups:
  - name: microservices-alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Servicio caído: {{ $labels.job }}"
          description: "Prometheus no puede scrapear el servicio {{ $labels.job }} en la instancia {{ $labels.instance }}."

      - alert: HighErrorRate
        expr: |
          (
            sum by (job) (
              rate(http_server_requests_seconds_count{status=~"5..", uri!~".*actuator.*"}[1m])
            )
            /
            sum by (job) (
              rate(http_server_requests_seconds_count{uri!~".*actuator.*"}[1m])
            )
          ) * 100 > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Alta tasa de errores 5xx en {{ $labels.job }}"
          description: "El servicio {{ $labels.job }} tiene más de 10% de errores 5xx durante el último minuto."

      - alert: HighLatencyP95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, job) (
              rate(http_server_requests_seconds_bucket{uri!~".*actuator.*"}[5m])
            )
          ) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Alta latencia p95 en {{ $labels.job }}"
          description: "El servicio {{ $labels.job }} tiene latencia p95 mayor a 1 segundo."