{
 "title": "Vista general del sistema",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Servicios UP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (job) (up == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate global %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_server_requests_seconds_count{status=~\"5..\", uri!~\".*actuator.*\"}[5m]))\r\n/\r\n  sum(rate(http_server_requests_seconds_count{uri!~\".*actuator.*\"}[5m]))\r\n) * 100\r\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia p95 global",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[5m])\r\n  )\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errores 5xx por microservicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (\r\n  rate(http_server_requests_seconds_count{status=~\"5..\", uri!~\"/actuator/.*\"}[1m])\r\n) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia p95 por microservicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, job) (\r\n    rate(http_server_requests_seconds_bucket{uri!~\"/actuator/.*\"}[5m])\r\n  )\r\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests por microservicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (\r\n rate(http_server_requests_seconds_count{uri!~\"/actuator/.*\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap usado % por microservicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (job) (jvm_memory_used_bytes{area=\"heap\"})\n/\n  clamp_min(sum by (job) (jvm_memory_max_bytes{area=\"heap\"}), 1)\n) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Errores 4xx por microservicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, status) (\n  rate(http_server_requests_seconds_count{status=~\"4..\", uri!~\".*actuator.*\"}[1m])\n) or on() vector(0)",
     "legendFormat": "{{job}} {{status}}"
    }
   ]
  },
  {
   "title": "CPU % (0–100) por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job) (process_cpu_usage * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}